### ISSUE TITLE
Flaky Rust Tests

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive-rs#104]
We're seeing an issue with `calculate_absolute_max_short_execute` where it is failing with a contract revert.

**Comment by dpaiton** [comment]
`test_calculate_implied_rate` just failed locally for me with this error:

```
---- short::open::tests::test_calculate_implied_rate stdout ----
Error: error sending request for url (http://localhost:54283/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```

**Comment by dpaiton** [comment]
I'm seeing these failures on `main` as well:

`short::open::tests::test_calculate_implied_rate`
`short::max::tests::fuzz_calculate_max_short_no_budget`
`short::max::tests::fuzz_calculate_max_short_no_budget`


```
---- short::open::tests::test_calculate_implied_rate stdout ----
Error: Contract call reverted with data: 0x4e487b710000000000000000000000000000000000000000000000000000000000000011

Location:
crates/hyperdrive-math/src/test_utils/agent.rs:87:25
```

```
thread 'short::max::tests::fuzz_calculate_max_short_no_budget' panicked at crates/hyperdrive-math/src/short/max.rs:572:21:
assertion `left == right` failed
  left: 1612481802949418
 right: 1612481802949419
 
stack backtrace:
...

21:        0x1029071c8 - hyperdrive_math::short::max::tests::fuzz_calculate_max_short_no_budget::{{closure}}::h99a8c3c093389417
                       at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:572:21
...

42:        0x102a6cd6c - hyperdrive_math::short::max::tests::fuzz_calculate_max_short_no_budget::h94769db016bfe70f
                       at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:521:9
43:        0x1029064d8 - hyperdrive_math::short::max::tests::fuzz_calculate_max_short_no_budget::{{closure}}::hfd2f1de83bb24989
                       at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:516:54
```

```
thread 'short::max::tests::fuzz_calculate_max_short_no_budget' panicked at /Users/dylan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/primitive-types-0.12.2/src/lib.rs:38:1:
arithmetic operation overflow
stack backtrace:

...

  21:        0x1029ae5b8 - hyperdrive_math::short::max::<impl hyperdrive_math::State>::solvency_after_short::h6af99fa04d82bea8
                               at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:447:13
  22:        0x1029ac304 - hyperdrive_math::short::max::<impl hyperdrive_math::State>::absolute_max_short::h22f8f7b6bfee9d44
                               at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:296:12
  23:        0x1029489d8 - hyperdrive_math::short::max::<impl hyperdrive_math::State>::calculate_max_short::hff6ee0a43f6f1a50
                               at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:83:13
  24:        0x1029091bc - hyperdrive_math::short::max::tests::fuzz_calculate_max_short_no_budget::{{closure}}::{{closure}}::h64ae12ac0ce5949b
                               at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:535:17

  29:        0x102908848 - hyperdrive_math::short::max::tests::fuzz_calculate_max_short_no_budget::{{closure}}::h99a8c3c093389417
                               at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:534:26

  50:        0x102a6cd6c - hyperdrive_math::short::max::tests::fuzz_calculate_max_short_no_budget::h94769db016bfe70f
                               at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:521:9
  51:        0x1029064d8 - hyperdrive_math::short::max::tests::fuzz_calculate_max_short_no_budget::{{closure}}::hfd2f1de83bb24989
                               at /Users/dylan/code/delv/hyperdrive-rs/crates/hyperdrive-math/src/short/max.rs:516:54

```

**Comment by dpaiton** [comment]
Just got two more of them on main branch:
```

failures:

---- lp::add::tests::fuzz_test_calculate_add_liquidity stdout ----
Error: Contract call reverted with data: 0x4e487b710000000000000000000000000000000000000000000000000000000000000011

Location:
    crates/hyperdrive-math/src/test_utils/agent.rs:87:25

---- short::open::tests::test_calculate_implied_rate stdout ----
Error: Contract call reverted with data: 0x4e487b710000000000000000000000000000000000000000000000000000000000000011

Location:
    crates/hyperdrive-math/src/test_utils/agent.rs:87:25
    ```

**Comment by dpaiton** [comment]
another one failing on main 
```
---- short::max::tests::fuzz_calculate_max_short stdout ----
thread 'short::max::tests::fuzz_calculate_max_short' panicked at crates/hyperdrive-math/src/short/max.rs:742:17:
expected (base=72369083.950666811963261164) < (budget=72942398.328880144557334009) * 0.001000000000000000 = 72942.398328880144557334
```

**Comment by dpaiton** [comment]
Regarding the contract call reverted error: 

The contract error is a FixedPoint underflow due to subtraction happening in the [`MockER4626.sol::_getAccruedInterest()`](https://github.com/delvtech/hyperdrive/blob/main/contracts/test/MockERC4626.sol#L188) function:

```
function _getAccruedInterest() internal view returns (uint256) {
        if (_rate == 0) {
            return 0;
        }

        // base_balance = base_balance * (1 + r * t)
        uint256 timeElapsed = (block.timestamp - _lastUpdated).divDown(
            365 days
        );
        uint256 accrued = asset.balanceOf(address(this)).mulDown(
            _rate.mulDown(timeElapsed)
        );
        return accrued;
    }
```

The `block.timestamp - _lastUpdated` logic is failing because `_lastUpdated` is one block ahead of `block.timestamp`.

This is happening intermittently in any test that uses `chain.snapshot()` and `chain.revert()` (which is **almost all tests**). This happens [here](https://github.com/delvtech/hyperdrive-rs/blob/main/crates/test-utils/src/chain.rs#L133-L151) in the rust repo.

The bug is hard to reproduce because tests can pass 100s of times and then fail. Somehow adding `println` or `console.log` statements here and there makes it less likely to happen. So tests that run faster might increase the likelihood of failure. However, it can also happen in the normal build mode (not `--release`) & without print statements.

I tried advancing time after the revert, minting blocks, making RPCs to get block info, and including a `sleep` when the revert happens. None of these consistently fix the problem. It's also worth noting that the same command in our Python tests is not causing this problem. We do the same thing where we use [RPC `evm` calls](https://github.com/delvtech/agent0/blob/main/src/agent0/core/hyperdrive/interactive/local_chain.py#L431) to snapshot and revert in loops in the tests.

The test that is most consistently failing was `test_calculate_implied_rate`, followed by `fuzz_calculate_absolute_max_short_execute`. Both of these include time advancement & adjusting the variable rate. I think this is the key: any test that does this has trouble reverting.

I'm not sure how to fix this problem yet. But one thing we can do is make an isolated rust test that has nothing to do with hyperdrive, which we can then post as an issue on the foundry github.

**Comment by wakamex** [comment]
Why don't we just add a check for this edge-case which represents a broken state of the world into MockERC4626? We have full control over that function, and it's there just to facilitate our testing.

**Comment by dpaiton** [comment]
https://github.com/delvtech/hyperdrive/pull/1040 fixes this, following @wakamex 's suggestion.

I moved the max short issue to https://github.com/delvtech/hyperdrive-rs/issues/121

This issue is now resolved.
